kafka:
  consumer:
    bootstrap-servers: 127.0.0.1:9092
    group-id: test
    topic: mask-tweets-input
    batch-interval: 10
    auto-offset: earliest
    client-id: earliest

api:
  url: https://api.cohere.ai/baseline-squid/similarity
  token: xxx
  anchor: masks are taking away freedom
